sudo: required
language: cpp
cache:
  ccache: true

before_install:
  - bash build.sh before-install

notifications:
  email:
    recipients:
      - glc12125@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

jobs:
  include:
    - stage: Core Build
      env: TASK="build"
      compiler: gcc
      script: bash build.sh $TASK